license = "${mod_license}"
issueTrackerURL = "https://github.com/YOUWILLDIE666/uwu/issues"

[[mods]] #mandatory
modId = "${mod_id}" #mandatory
version = "${mod_version}" #mandatory
displayName = "${mod_name}" #mandatory
updateJSONURL = "https://raw.githubusercontent.com/YOUWILLDIE666/uwu/refs/heads/1.21.8/updatecheck/updates.json"
displayURL = "https://github.com/YOUWILLDIE666/uwu"
#logoFile="examplemod.png" // i will uhmmmmm idk
authors = "${mod_authors}"
description = '''${mod_description}'''

[[mixins]]
config = "${mod_id}.mixins.json"
[[dependencies.${ mod_id }]]
modId = "neoforge" #mandatory
type = "required" #mandatory
versionRange = "[${neo_version},)" #mandatory
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
